FROM twdps/circleci-base-image:slim-3.3.0

LABEL maintainer=<nchenewe@thoughtworks.com>

ENV CONFTEST_VERSION=0.30.0

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

# hadolint ignore=DL4001,DL3004,DL3047
RUN sudo bash -c "echo 'APT::Get::Assume-Yes \"true\";' > /etc/apt/apt.conf.d/90circleci" && \
    sudo bash -c "echo 'DPkg::Options \"--force-confnew\";' >> /etc/apt/apt.conf.d/90circleci" && sudo apt-get update && \
    sudo apt-get install --no-install-recommends -y \
            curl=7.82.0-2 \
            wget=1.21.3-1 \
            gnupg=2.2.27-3 \
            apt-transport-https=2.4.4 \
            lsb-release=11.1.0 \
            ruby-full=1:3.0+1 \
            gcc=4:11.2.0-2 \
            g++=4:11.2.0-2 \
            make=4.3-4.1 \
            libcurl3-gnutls=7.82.0-2 && \
    sudo bash -c "curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg" && \
    sudo bash -c "echo \"deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable\" | tee /etc/apt/sources.list.d/docker.list > /dev/null" && sudo apt-get update && \
    sudo apt-get install --no-install-recommends -y \
                 docker-ce=5:20.10.14~3-0~debian-bullseye \
                 docker-ce-cli=5:20.10.14~3-0~debian-bullseye \
                 containerd.io=1.6.2~ds1-1 && \
    sudo bash -c "curl -sL https://deb.nodesource.com/setup_16.x | bash - " && \
    sudo apt-get install --no-install-recommends -y \
                 nodejs=16.14.2-deb-1nodesource1 && \
    sudo apt-get clean && \
    sudo rm -rf /var/lib/apt/lists/* && \
    sudo bash -c "sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen && locale-gen" && \
    sudo npm install -g \
             snyk@1.893.0 \
             bats@1.6.0 \
             github-release-notes@0.17.3 && \
    sudo gem install --no-document \
             inspec-bin:5.10.5 && \
    wget https://github.com/open-policy-agent/conftest/releases/download/v${CONFTEST_VERSION}/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz && \
    tar xzf conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz && \
    sudo apt remove -y gnupg && \
    sudo mv conftest /usr/local/bin && sudo rm ./*

COPY inspec /etc/chef/accepted_licenses/inspec

USER circleci
